hostname = gateway.mashibing.com

# > 马士兵学习 hostname = gateway.mashibing.com
^https:\/\/gateway\.mashibing\.com\/edu-course\/(coursePackage\/app\/1|app\/systemCourse|courseWeb) url script-response-body https://raw.githubusercontent.com/BOBANDJOB/PrivateQX/main/Scripts/msb.js
